language: scala

services:
  - docker

before_install:
  - docker build -t perftest:v1.0 .

script:
  - docker run -v $(pwd)/gatling-result:/opt/load-test/target/gatling perftest:v1.0 sbt gatling:test